### ISSUE TITLE
Can I use this with vue-cli aka webpack?

### ISSUE THREAD

**Issue by johnnyshankman** [policyfly/vue-script-tsc#9]
How would I go about inserting type checking as a step before it tries to build?

**Comment by BenShelton** [comment]
There's no plugin for `vue-cli` but you can just run it before the build step. This is the same as would be done for Vite:

```json
"scripts": {
  "build": "vue-script-tsc --root . && vue-cli-service build"
}
```

If you're doing that you may want to disable webpack's slow type checking too, as then you'll be running type checking twice, once with `vue-script-tsc` and then again in the build step because of `fork-ts-checker-webpack-plugin`. Here is mentioned one way to remove it though I have not tried it myself: https://github.com/vuejs/vue-cli/issues/3157#issuecomment-629610739 (ignore the comment below saying not to do this, yes you're skipping type errors in webpack but that's because you're doing it elsewhere)

Let me know if this works and I can add a note in the README about this specific use case.

**Comment by BenShelton** [comment]
Nice! Glad you got it working, in that case I'm gonna close this issue.
